// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sila-chain/Sila-Consensus-Core/v7/validator/client/iface (interfaces: SilaChainClient)
//
// Generated by this command:
//
//	mockgen -package=validator_mock -destination=testing/validator-mock/sila_chain_client_mock.go github.com/sila-chain/Sila-Consensus-Core/v7/validator/client/iface SilaChainClient
//

// Package validator_mock is a generated GoMock package.
package validator_mock

import (
	context "context"
	reflect "reflect"

	validator "github.com/sila-chain/Sila-Consensus-Core/v7/consensus-types/validator"
	sila "github.com/sila-chain/Sila-Consensus-Core/v7/proto/sila/v1alpha1"
	iface "github.com/sila-chain/Sila-Consensus-Core/v7/validator/client/iface"
	gomock "go.uber.org/mock/gomock"
)

// MockSilaChainClient is a mock of SilaChainClient interface.
type MockSilaChainClient struct {
	ctrl     *gomock.Controller
	recorder *MockSilaChainClientMockRecorder
	isgomock struct{}
}

// MockSilaChainClientMockRecorder is the mock recorder for MockSilaChainClient.
type MockSilaChainClientMockRecorder struct {
	mock *MockSilaChainClient
}

// NewMockSilaChainClient creates a new mock instance.
func NewMockSilaChainClient(ctrl *gomock.Controller) *MockSilaChainClient {
	mock := &MockSilaChainClient{ctrl: ctrl}
	mock.recorder = &MockSilaChainClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSilaChainClient) EXPECT() *MockSilaChainClientMockRecorder {
	return m.recorder
}

// ValidatorCount mocks base method.
func (m *MockSilaChainClient) ValidatorCount(arg0 context.Context, arg1 string, arg2 []validator.Status) ([]iface.ValidatorCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorCount", arg0, arg1, arg2)
	ret0, _ := ret[0].([]iface.ValidatorCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatorCount indicates an expected call of ValidatorCount.
func (mr *MockSilaChainClientMockRecorder) ValidatorCount(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorCount", reflect.TypeOf((*MockSilaChainClient)(nil).ValidatorCount), arg0, arg1, arg2)
}

// ValidatorPerformance mocks base method.
func (m *MockSilaChainClient) ValidatorPerformance(arg0 context.Context, arg1 *sila.ValidatorPerformanceRequest) (*sila.ValidatorPerformanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorPerformance", arg0, arg1)
	ret0, _ := ret[0].(*sila.ValidatorPerformanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatorPerformance indicates an expected call of ValidatorPerformance.
func (mr *MockSilaChainClientMockRecorder) ValidatorPerformance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorPerformance", reflect.TypeOf((*MockSilaChainClient)(nil).ValidatorPerformance), arg0, arg1)
}
