// Copyright 2020 Sila Labs.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/sila/ext/options.proto

package ext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto_sila_ext_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "sila.eth.ext.cast_type",
		Tag:           "bytes,50000,opt,name=cast_type",
		Filename:      "proto/sila/ext/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "sila.eth.ext.ssz_size",
		Tag:           "bytes,50001,opt,name=ssz_size",
		Filename:      "proto/sila/ext/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "sila.eth.ext.ssz_max",
		Tag:           "bytes,50002,opt,name=ssz_max",
		Filename:      "proto/sila/ext/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "sila.eth.ext.spec_name",
		Tag:           "bytes,50003,opt,name=spec_name",
		Filename:      "proto/sila/ext/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string cast_type = 50000;
	E_CastType = &file_proto_sila_ext_options_proto_extTypes[0]
	// optional string ssz_size = 50001;
	E_SszSize = &file_proto_sila_ext_options_proto_extTypes[1]
	// optional string ssz_max = 50002;
	E_SszMax = &file_proto_sila_ext_options_proto_extTypes[2]
	// optional string spec_name = 50003;
	E_SpecName = &file_proto_sila_ext_options_proto_extTypes[3]
)

var File_proto_sila_ext_options_proto protoreflect.FileDescriptor

const file_proto_sila_ext_options_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/sila/ext/options.proto\x12\fsila.eth.ext\x1a google/protobuf/descriptor.proto:<\n" +
	"\tcast_type\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\tR\bcastType::\n" +
	"\bssz_size\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\asszSize:8\n" +
	"\assz_max\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\tR\x06sszMax:<\n" +
	"\tspec_name\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\tR\bspecNameBq\n" +
	"\x10org.Sila.Eth.extB\fOptionsProtoP\x01Z/github.com/sila-chain/Sila-Prysm-Core/v7/proto/sila/ext\xaa\x02\fSila.Eth.ext\xca\x02\fSila\\Eth\\extb\x06proto3"

var file_proto_sila_ext_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_proto_sila_ext_options_proto_depIdxs = []int32{
	0, // 0: sila.eth.ext.cast_type:extendee -> google.protobuf.FieldOptions
	0, // 1: sila.eth.ext.ssz_size:extendee -> google.protobuf.FieldOptions
	0, // 2: sila.eth.ext.ssz_max:extendee -> google.protobuf.FieldOptions
	0, // 3: sila.eth.ext.spec_name:extendee -> google.protobuf.FieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sila_ext_options_proto_init() }
func file_proto_sila_ext_options_proto_init() {
	if File_proto_sila_ext_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sila_ext_options_proto_rawDesc), len(file_proto_sila_ext_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_proto_sila_ext_options_proto_goTypes,
		DependencyIndexes: file_proto_sila_ext_options_proto_depIdxs,
		ExtensionInfos:    file_proto_sila_ext_options_proto_extTypes,
	}.Build()
	File_proto_sila_ext_options_proto = out.File
	file_proto_sila_ext_options_proto_goTypes = nil
	file_proto_sila_ext_options_proto_depIdxs = nil
}
