package verification

const (
	RequireBlobIndexInBounds Requirement = iota
	RequireNotFromFutureSlot
	RequireSlotAboveFinalized
	RequireValidProposerSignature
	RequireSidecarParentSeen
	RequireSidecarParentValid
	RequireSidecarParentSlotLower
	RequireSidecarDescendsFromFinalized
	RequireSidecarInclusionProven
	RequireSidecarKzgProofVerified
	RequireSidecarProposerExpected

	// Data columns specific.
	RequireValidFields
	RequireCorrectSubnet
	RequireBlockSeenGloas
	RequireSlotMatchesBlockGloas
	RequireValidFieldsGloas
	RequireSidecarKzgProofVerifiedGloas
	RequireNotSeenGloas

	// Payload attestation specific.
	RequireCurrentSlot
	RequireMessageNotSeen
	RequireValidatorInPTC
	RequireBlockRootSeen
	RequireBlockSlotMatches
	RequireBlockRootValid
	RequireSignatureValid

	// Execution payload envelope specific.
	RequireBuilderValid
	RequirePayloadHashValid
	RequireSilaRequestsRootValid
	RequireEnvelopeSlotAboveFinalized
	RequireEnvelopeSlotMatchesBlock
	RequireBuilderSignatureValid

	// Execution payload bid specific.
	RequireBidCurrentOrNextSlot
	RequireBidBuilderActive
	RequireBidSilaPaymentZero
	RequireBidFeeRecipientMatches
	RequireBidGasLimitCompatible
	RequireBidParentBlockRootSeen
	RequireBidSlotHigherThanParent
	RequireBidParentBlockHashValid
	RequireBidBuilderCanCover
	RequireBidSignatureValid

	// Signed proposer preferences specific.
	RequireProposerPreferencesCurrentOrNextEpoch
	RequireProposerPreferencesDependentRootSeen
	RequireProposerPreferencesProposalSlotValid
	RequireProposerPreferencesSignatureValid
)
